### ISSUE TITLE
the fixed [35:-33,32:-36] region

### ISSUE THREAD

**Issue by T-xu** [yangxy/GPEN#142]
I wonder know why the roi region is cropped like this.Why you used the fixed [35:-33,32:-36] region instead of face detection to crop img?Look forward to your reply,thanks.
![1655262630024](https://user-images.githubusercontent.com/46927238/173728659-d2209142-68f1-4b3e-9a9e-1e0f8008fd3d.jpg)

**Comment by yangxy** [comment]
The purpose is to crop the interesting region for face recognition due to the difference in input regions required for GPEN and Arcface. Thanks to the feature of face alignment used in GPEN, this can be done with a fixed region, which is commonly used by many works such as [styleclip](https://github.com/orpatashnik/StyleCLIP/blob/main/criteria/id_loss.py).

Yes, a face detector can achieve that too. But it's much heavier.
